const CountryArray = [
  {index: 1,value: "Afghanistan", label: "Afghanistan" },
  {index: 2, value: "Albania", label: "Albania" },
  {index: 3,value: "Algeria", label: "Algeria" },
  {index: 4,value: "Andorra", label: "Andorra" },
  {index: 5,value: "Angola", label: "Angola" },
  {index: 6,value: "AntiguaandBarbuda", label: "AntiguaandBarbuda" },
  {index: 7, value: "Armenia", label: "Armenia" },
  {index: 8,value: "Australia", label: "Australia" },
  {index: 9, value: "Austria", label: "Austria" },
  {index: 10,value: "Azerbaijan", label: "Azerbaijan" },
  {index: 11,value: "Bahamas", label: "Bahamas" },
  {index: 12,value: "Bahrain", label: "Bahrain" },
  {index: 13,value: "Bangladesh", label: "Bangladesh" },
  {index: 14,value: "Barbados", label: "Barbados" },
  {index: 15,value: "Belarus", label: "Belarus" },
  {index: 16,value: "Belgium", label: "Belgium" },
  {index: 17,value: "Belize", label: "Belize" },
  {index: 18,value: "Benin", label: "Benin" },
  {index: 19, value: "Bhutan", label: "Bhutan" },
  {index: 20, value: "Bolivia", label: "Bolivia" },
  {index: 21, value: "BosniaandHerzegovina", label: "Bosnia and Herzegovina" },
  {index: 22, value: "Botswana", label: "Botswana" },
  {index: 23, value: "Brazil", label: "Brazil" },
  {index: 24, value: "Brunei", label: "Brunei" },
  {index: 25, value: "Bulgaria", label: "Bulgaria" },
  {index: 26, value: "BurkinaFaso", label: "BurkinaFaso" },
  {index: 27, value: "Burundi", label: "Burundi" },
  {index: 28, value: "Cameroon", label: "Cameroon" },
  {index: 29, value: "Canada", label: "Canada" },
  {index: 30, value: "Chad", label: "Chad" },
  {index: 31, value: "Chile", label: "Chile" },
  {index: 32, value: "China", label: "China" },
  {index: 33, value: "Colombia", label: "Colombia" },
  {index: 34, value: "Congo", label: "Congo" },
  {index: 35, value: "Croatia", label: "Croatia" },
  {index: 36, value: "Denmark", label: "Denmark" },
  {index: 37, value: "Dominica", label: "Dominica" },
  {index: 38, value: "Egypt", label: "Egypt" },
  {index: 39, value: "Ecuador", label: "Ecuador" },
  {index: 40, value: "Ethiopia", label: "Ethiopia" },
  {index: 41, value: "France", label: "France" },
  {index: 42, value: "Georgia", label: "Georgia" },
  {index: 43, value: "Greece", label: "Greece" },
  {index: 44, value: "Germany", label: "Germany" },
  {index: 45, value: "Guatemala", label: "Guatemala" },
  {index: 46, value: "Hungary", label: "Hungary" },
  {index: 47, value: "Iceland", label: "Iceland" },
  {index: 48, value: "Indonesia", label: "Indonesia" },
  {index: 49, value: "Iran", label: "Iran" },
  {index: 50, value: "Ireland", label: "Ireland" },
  {index: 51, value: "Israel", label: "Israel" },
  {index: 52, value: "Italy", label: "Italy" },
  {index: 53, value: "Jamaica", label: "Jamaica" },
  {index: 54, value: "Japan", label: "Japan" },
  {index: 55, value: "Jordan", label: "Jordan" },
  {index: 56, value: "Kazakhstan", label: "Kazakhstan" },
  {index: 57, value: "Kuwait", label: "Kuwait" },
  {index: 58, value: "Lebanon", label: "Lebanon" },
  {index: 59, value: "Laos", label: "Laos" },
  {index: 60, value: "Latvia", label: "Latvia" },
  {index: 61, value: "Kuwait", label: "Kuwait" },
  {index: 62, value: "Lebanon", label: "Lebanon" },
  {index: 63, value: "Kazakhstan", label: "Kazakhstan" },
  {index: 64, value: "Kuwait", label: "Kuwait" },
  {index: 65, value: "Lebanon", label: "Lebanon" },
  {index: 66, value: "Lesotho", label: "Lesotho" },
  {index: 67, value: "Liechtenstein", label: "Liechtenstein" },
  {index: 68, value: "Luxembourg", label: "Luxembourg" },
  {index: 69, value: "Madagascar", label: "Madagascar" },
  {index: 70, value: "Kazakhstan", label: "Kazakhstan" },
  {index: 71, value: "Kuwait", label: "Kuwait" },
  {index: 72, value: "Lebanon", label: "Lebanon" },
  {index: 73, value: "Malawi", label: "Malawi" },
  {index: 74, value: "Malaysia", label: "Malaysia" },
  {index: 75, value: "Mexico", label: "Mexico" },
  {index: 76, value: "Monaco", label: "Monaco" },
  {index: 77, value: "Montenegro", label: "Montenegro" },
  {index: 78, value: "Morocco", label: "Morocco" },
  {index: 79, value: "Myanmar", label: "Myanmar" },
  {index: 80, value: "Nepal", label: "Nepal" },
  {index: 81, value: "Netherlands", label: "Netherlands" },
  {index: 82, value: "NewZealand", label: "NewZealand" },
  {index: 83, value: "Niger", label: "Niger" },
  {index: 84, value: "Nigeria", label: "Nigeria" },
  {index: 85, value: "Mexico", label: "Mexico" },
  {index: 86, value: "Norway", label: "Norway" },
  {index: 87, value: "Oman", label: "Oman" },
  {index: 88, value: "Panama", label: "Panama" },
  {index: 89, value: "Paraguay", label: "Paraguay" },
  {index: 90, value: "Peru", label: "Peru" },
  {index: 91, value: "Poland", label: "Poland" },
  {index: 92, value: "Philippines", label: "Philippines" },
  {index: 93, value: "Portugal", label: "Portugal" },
  {index: 94, value: "Qatar", label: "Qatar" },
  {index: 95, value: "Mexico", label: "Mexico" },
  {index: 96, value: "Romania", label: "Romania" },
  {index: 97, value: "Russia", label: "Russia" },
  {index: 98, value: "Samoa", label: "Samoa" },
  {index: 99, value: "SaudiArabia", label: "SaudiArabia" },
  {index: 100, value: "Senegal", label: "Senegal" },
  {index: 101, value: "Slovakia", label: "Slovakia" },
  {index: 102, value: "Slovenia", label: "Slovenia" },
  {index: 103, value: "Singapore", label: "Singapore" },
  {index: 104, value: "SouthKorea", label: "SouthKorea" },
  {index: 105, value: "SouthAfrica", label: "SouthAfrica" },
  {index: 106, value: "Spain", label: "Spain" },
  {index: 107, value: "Sudan", label: "Sudan" },
  {index: 108, value: "Sweden", label: "Sweden" },
  {index: 109, value: "Switzerland", label: "Switzerland" },
  {index: 110, value: "Syria", label: "Syria" },
  {index: 111, value: "Tajikistan", label: "Tajikistan" },
  {index: 112, value: "Thailand", label: "Thailand" },
  {index: 113, value: "Tunisia", label: "Tunisia" },
  {index: 114, value: "Turkey", label: "Turkey" },
  {index: 115, value: "Turkmenistan", label: "Turkmenistan" },
  {index: 116, value: "UnitedArabEmirates", label: "UnitedArabEmirates" },
  {index: 117, value: "UnitedKingdom", label: "UnitedKingdom" },
  {index: 118, value: "USA", label: "USA" },
  {index: 119, value: "Uruguay", label: "Uruguay" },
  {index: 120, value: "Uzbekistan", label: "Uzbekistan" },
  {index: 121, value: "Venezuela", label: "Venezuela" },
  {index: 122, value: "Vietnam", label: "Vietnam" },
  {index: 123, value: "Yemen", label: "Yemen" },
  {index: 124, value: "Zambia", label: "Zambia" },
  {index: 125, value: "Zimbabwe", label: "Zimbabwe" },

]


export default CountryArray;